---
- name: Patch all CentOS & RHEL servers
  hosts: prod
#  environment: "{{ proxy_env }}"

  vars_files:
    - /home/nscsvc/vars.yml
#    - /home/nscsvc/vault.yml

  tasks:

    - name: Stop guardian service
      service:
        name: guardian
        state: stopped
      ignore_errors: yes
      tags: updates

    - name: Create reports directory
      file:
        path: ~/patching_reports 
        state: directory
        mode: '0755'
      tags: reports

    - name: Delete old reports files
      args:
        warn: false
      shell: /bin/rm -f ~/patching_reports/*
      tags: reports

    - name: Create new reports files
      file:
        path: ~/patching_reports/alvaria_updates{{ item }}
        state: touch
        mode: '0666'
      with_items:
        - -a.tmp
        - -b.tmp
        - .report.body
        - .report.header
        - .report
      tags: reports

    - name: Download CentOS repos
      yum:
        name: https://atllxyum1.noblesys.com/alvaria-release-latest.rpm
        state: latest
#        validate_certs: no
      when: ansible_facts['distribution'] == "CentOS"
      tags: repos

    - name: Delete old repository backup if present
      file:
        path: /etc/yum.repos.d.bak
        state: absent
      when: ansible_facts['distribution'] == "RedHat"

    - name: Backup directory /etc/yum.repos.d into /etc/yum.repos.d.bak
      args:
        warn: false
      shell: /bin/cp -a /etc/yum.repos.d /etc/yum.repos.d.bak
      when: ansible_facts['distribution'] == "RedHat"

    - name: Delete old repositories
      args:
        warn: false
      shell: /bin/rm -f /etc/yum.repos.d/*
      when: ansible_facts['distribution'] == "RedHat"

    - name: Download RHEL repo
      get_url:
        url: https://atllxyum1.noblesys.com/repo/rhel/alvaria-rhel.repo
        dest: /etc/yum.repos.d
        mode: '0755'
      when: ansible_facts['distribution'] == "RedHat"
      tags: repos

    - name: Set kernel retention to 2 versions
      lineinfile:
        path: /etc/yum.conf
        regexp: '^installonly_limit=(.*)'
        line: 'installonly_limit=2'
        backrefs: yes
      tags: updates

    - name: Run yum clean all
      args:
        warn: false
      command: yum --enablerepo="*" clean all
      tags: updates

    - name: Create report header
      shell: |
        echo "Alvaria OS Patching Report" > ~/patching_reports/alvaria_updates.report.header
        echo "--------------------------------" >> ~/patching_reports/alvaria_updates.report.header
        echo "Date          : `date`" >> ~/patching_reports/alvaria_updates.report.header
        echo "Machine       : ${HOSTNAME}" >> ~/patching_reports/alvaria_updates.report.header
        echo " " >> ~/patching_reports/alvaria_updates.report.header
        echo "Starting OS Version    : `cat /etc/redhat-release`" >> ~/patching_reports/alvaria_updates.report.header
        echo "Starting Kernel Version: `uname -r`" >> ~/patching_reports/alvaria_updates.report.header
        echo " " >> ~/patching_reports/alvaria_updates.report.header
      tags: reports

    - name: Generate list of packages and their version numbers for updates
      args:
        warn: False
      shell: |
        /usr/bin/yum list updates|egrep ".i386|.i686|.x86_64|.noarch|.src"|sed "s/.i386//"|sed "s/.noarch//"|sed "s/.x86_64//"|sed "s/.src//"|grep -v Excluding > ~/patching_reports/alvaria_updates-a.tmp
        cat ~/patching_reports/alvaria_updates-a.tmp|awk '{ print $1 } ' > ~/patching_reports/alvaria_updates-b.tmp
   
    - name: Count packages
      shell: cat ~/patching_reports/alvaria_updates-a.tmp|wc -l
      register: package_count
      tags: updates

    - name: Create report body
      shell: |
        echo "PACKAGES TO BE UPDATED" >> ~/patching_reports/alvaria_updates.report.body
        echo "----------------------" >> ~/patching_reports/alvaria_updates.report.body
        cat ~/patching_reports/alvaria_updates-b.tmp
      register: package_name
      when: package_count.stdout | int > 0
      tags: reports

    - name: Populate report body with package names and versions
      shell: |
        echo -e "Package: {{ item }}\nCurrent Version: `rpm -q --queryformat '%{VERSION}-%{RELEASE}\n' {{ item }}|tail -1`  New Version: `cat ~/patching_reports/alvaria_updates-a.tmp|grep -w {{ item }}|head -1|awk '{ print $2 } '`\n" >> ~/patching_reports/alvaria_updates.report.body
      loop: "{{ package_name.stdout_lines }}"
      when: package_count.stdout | int > 0
      changed_when: False
      tags: reports

    - name: Populate report body if no updates available
      shell: echo "SYSTEM UP TO DATE - NO UPDATES AVAILABLE" >> ~/patching_reports/alvaria_updates.report.body
      when: package_count.stdout | int == 0
      tags: reports

    - name: Check memory
      shell: free -m | grep Mem | awk '{ print $4 }'
      register: free_mem
      tags: updates

    - name: Clear memory
      shell: sync; echo 1 > /proc/sys/vm/drop_caches
      when: free_mem.stdout | int < 384
      tags: updates

    - name: Recheck memory
      shell: free -m | grep Mem | awk '{ print $4 }'
      register: free_mem2
      tags: updates

    - name: Report systems without enough memory
      debug:
        msg: "WARNING: This system does not have enough memory to patch. Please reboot and try again."
      when: free_mem2.stdout | int < 384
      failed_when: free_mem2.stdout | int < 384
      tags: updates

    - name: Upgrade packages via yum
      yum:
        disable_excludes: all
        name: '*'
        state: latest
        skip_broken: yes
        update_cache: yes
      register: yumcommandout
      when: ansible_facts['os_family'] == "RedHat" and free_mem2.stdout | int >= 384
      tags: updates

    - name: Print errors if yum failed
      debug:
        msg: "yum command produced errors"
      when: yumcommandout is not defined
      tags: updates

    - name: Make sure kernel installed
      tags: 
      - updates
      - kernel

      block:
        - name: Check if new kernel was installed
          shell: /usr/bin/needs-restarting -r || /bin/true
          register: check_kernel
          changed_when: False

        - name: Find new initramfs version
          shell: "needs-restarting -r | grep kernel | awk '{ print $3 }'"
          register: initramfs
          when: "'kernel -> 3' in check_kernel.stdout"
          changed_when: False

        - name: Make sure new initramfs is present
          shell: "ls /boot/initramfs-{{ initramfs.stdout }}.x86_64.img"
          when: "'kernel -> 3' in check_kernel.stdout"
          changed_when: False

      rescue:
        - name: Recreate initramfs
          shell: dracut --kver `needs-restarting -r | grep kernel | awk '{ print $3 }'`.x86_64

    - name: Compile reports
      shell: |
        echo "Ending OS Version      : `cat /etc/redhat-release`" >> ~/patching_reports/alvaria_updates.report.header
        echo "Ending Kernel Version  : `needs-restarting -r | grep kernel | awk '{ print $3 }'`.x86_64" >> ~/patching_reports/alvaria_updates.report.header
        echo " " >> ~/patching_reports/alvaria_updates.report.header
        echo " " >> ~/patching_reports/alvaria_updates.report.header
        cat ~/patching_reports/alvaria_updates.report.header > ~/patching_reports/alvaria_updates.report
        cat ~/patching_reports/alvaria_updates.report.body >> ~/patching_reports/alvaria_updates.report
      tags: reports

    - name: Email reports
      shell: |
        /usr/local/bin/nscmail -s "`uname -n`: Alvaria OS Patching Results" -b ~/patching_reports/alvaria_updates.report -t "{{ item }}" -m mail.noblesys.com || /bin/true
      loop: "{{ email_addr }}"
      changed_when: False
      ignore_errors: yes
      tags: email
