---
- name: Time to recompile siphony
  hosts: 
#  environment: "{{ proxy_env }}"
  gather_facts: no
  tags: updates

  vars_files:
    - /home/nscsvc/vars.yml
#    - /home/nscsvc/vault.yml

  tasks:

    - name: Delete previous versions of recompile_siphony.sh
      file:
        path: /usr/src/recompile_siphony.sh
        state: absent

    - name: Download recompile_siphony script
      get_url:
        url: https://atllxyum1.noblesys.com/recompile_siphony.sh
        dest: /usr/src
        mode: '0755'

    - name: Starting long running op ( recompile_siphony.sh ) allow to run for 5 min, fire and forget
      command: /usr/src/recompile_siphony.sh
      async: 900
      poll: 0
      register: compile_status

    - name: Checking to see if recompile_siphony.sh is complete
      async_status:
        jid: "{{ compile_status.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 225
      delay: 15
