---
- name: Reboot all machines
  hosts: test
  gather_facts: no
  tags:
  - updates
  - kernel

  vars_files:
    - /home/user/vars.yml
   - /home/user/vault.yml

  tasks:

    - name: Restart server
      command: /sbin/shutdown -r +1 --no-wall
      async: 0
      poll: 0
      ignore_errors: true

