---
- name: Patch all CentOS & RHEL servers
  hosts: test
  become: yes
#  environment: "{{ proxy_env }}"

  vars_files:
    - /home/user/vars.yml
    - /home/user/vault.yml

  tasks:
    - name: Upgrade packages via yum
      yum:
        disable_excludes: all
        name: '*'
        state: latest
        skip_broken: yes
        update_cache: yes
      register: yumcommandout
      when: ansible_facts['os_family'] == "RedHat" and free_mem2.stdout | int >= 384
      tags: updates

    - name: Print errors if yum failed
      debug:
        msg: "yum command produced errors"
      when: yumcommandout is not defined
      tags: updates

