---
    - name: Check memory
      shell: free -m | grep Mem | awk '{ print $4 }'
      register: free_mem
      tags: updates

    - name: Clear memory
      shell: sync; echo 1 > /proc/sys/vm/drop_caches
      when: free_mem.stdout | int < 384
      tags: updates

    - name: Recheck memory
      shell: free -m | grep Mem | awk '{ print $4 }'
      register: free_mem2
      tags: updates

    - name: Report systems without enough memory
      debug:
        msg: "WARNING: This system does not have enough memory to patch. Please reboot and try again."
      when: free_mem2.stdout | int < 384
      failed_when: free_mem2.stdout | int < 384
      tags: updates


